/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.carservice.model.impl;

import com.carservice.model.CarReport;
import com.carservice.model.CarReportModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CarReport service. Represents a row in the &quot;Car_CarReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CarReportModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CarReportImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CarReportImpl
 * @generated
 */
@JSON(strict = true)
public class CarReportModelImpl
	extends BaseModelImpl<CarReport> implements CarReportModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a car report model instance should use the <code>CarReport</code> interface instead.
	 */
	public static final String TABLE_NAME = "Car_CarReport";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"carReportId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"carId", Types.BIGINT}, {"dealerId", Types.BIGINT},
		{"viewDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("carReportId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("carId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dealerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("viewDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Car_CarReport (uuid_ VARCHAR(75) null,carReportId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,carId LONG,dealerId LONG,viewDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Car_CarReport";

	public static final String ORDER_BY_JPQL =
		" ORDER BY carReport.userName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Car_CarReport.userName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEALERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERNAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CarReportModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _carReportId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCarReportId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _carReportId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CarReport.class;
	}

	@Override
	public String getModelClassName() {
		return CarReport.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CarReport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CarReport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarReport, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CarReport)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CarReport, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CarReport, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CarReport)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CarReport, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CarReport, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CarReport, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CarReport, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<CarReport, Object>>();

			attributeGetterFunctions.put("uuid", CarReport::getUuid);
			attributeGetterFunctions.put(
				"carReportId", CarReport::getCarReportId);
			attributeGetterFunctions.put("groupId", CarReport::getGroupId);
			attributeGetterFunctions.put("companyId", CarReport::getCompanyId);
			attributeGetterFunctions.put("userId", CarReport::getUserId);
			attributeGetterFunctions.put("userName", CarReport::getUserName);
			attributeGetterFunctions.put(
				"createDate", CarReport::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CarReport::getModifiedDate);
			attributeGetterFunctions.put("carId", CarReport::getCarId);
			attributeGetterFunctions.put("dealerId", CarReport::getDealerId);
			attributeGetterFunctions.put("viewDate", CarReport::getViewDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CarReport, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CarReport, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CarReport, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<CarReport, String>)CarReport::setUuid);
			attributeSetterBiConsumers.put(
				"carReportId",
				(BiConsumer<CarReport, Long>)CarReport::setCarReportId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<CarReport, Long>)CarReport::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CarReport, Long>)CarReport::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<CarReport, Long>)CarReport::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CarReport, String>)CarReport::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CarReport, Date>)CarReport::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CarReport, Date>)CarReport::setModifiedDate);
			attributeSetterBiConsumers.put(
				"carId", (BiConsumer<CarReport, Long>)CarReport::setCarId);
			attributeSetterBiConsumers.put(
				"dealerId",
				(BiConsumer<CarReport, Long>)CarReport::setDealerId);
			attributeSetterBiConsumers.put(
				"viewDate",
				(BiConsumer<CarReport, Date>)CarReport::setViewDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCarReportId() {
		return _carReportId;
	}

	@Override
	public void setCarReportId(long carReportId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_carReportId = carReportId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCarId() {
		return _carId;
	}

	@Override
	public void setCarId(long carId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_carId = carId;
	}

	@JSON
	@Override
	public long getDealerId() {
		return _dealerId;
	}

	@Override
	public void setDealerId(long dealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dealerId = dealerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDealerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("dealerId"));
	}

	@JSON
	@Override
	public Date getViewDate() {
		return _viewDate;
	}

	@Override
	public void setViewDate(Date viewDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_viewDate = viewDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CarReport.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CarReport.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CarReport toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CarReport>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CarReportImpl carReportImpl = new CarReportImpl();

		carReportImpl.setUuid(getUuid());
		carReportImpl.setCarReportId(getCarReportId());
		carReportImpl.setGroupId(getGroupId());
		carReportImpl.setCompanyId(getCompanyId());
		carReportImpl.setUserId(getUserId());
		carReportImpl.setUserName(getUserName());
		carReportImpl.setCreateDate(getCreateDate());
		carReportImpl.setModifiedDate(getModifiedDate());
		carReportImpl.setCarId(getCarId());
		carReportImpl.setDealerId(getDealerId());
		carReportImpl.setViewDate(getViewDate());

		carReportImpl.resetOriginalValues();

		return carReportImpl;
	}

	@Override
	public CarReport cloneWithOriginalValues() {
		CarReportImpl carReportImpl = new CarReportImpl();

		carReportImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		carReportImpl.setCarReportId(
			this.<Long>getColumnOriginalValue("carReportId"));
		carReportImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		carReportImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		carReportImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		carReportImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		carReportImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		carReportImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		carReportImpl.setCarId(this.<Long>getColumnOriginalValue("carId"));
		carReportImpl.setDealerId(
			this.<Long>getColumnOriginalValue("dealerId"));
		carReportImpl.setViewDate(
			this.<Date>getColumnOriginalValue("viewDate"));

		return carReportImpl;
	}

	@Override
	public int compareTo(CarReport carReport) {
		int value = 0;

		value = getUserName().compareTo(carReport.getUserName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CarReport)) {
			return false;
		}

		CarReport carReport = (CarReport)object;

		long primaryKey = carReport.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CarReport> toCacheModel() {
		CarReportCacheModel carReportCacheModel = new CarReportCacheModel();

		carReportCacheModel.uuid = getUuid();

		String uuid = carReportCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			carReportCacheModel.uuid = null;
		}

		carReportCacheModel.carReportId = getCarReportId();

		carReportCacheModel.groupId = getGroupId();

		carReportCacheModel.companyId = getCompanyId();

		carReportCacheModel.userId = getUserId();

		carReportCacheModel.userName = getUserName();

		String userName = carReportCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			carReportCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			carReportCacheModel.createDate = createDate.getTime();
		}
		else {
			carReportCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			carReportCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			carReportCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		carReportCacheModel.carId = getCarId();

		carReportCacheModel.dealerId = getDealerId();

		Date viewDate = getViewDate();

		if (viewDate != null) {
			carReportCacheModel.viewDate = viewDate.getTime();
		}
		else {
			carReportCacheModel.viewDate = Long.MIN_VALUE;
		}

		return carReportCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CarReport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CarReport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarReport, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CarReport)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CarReport>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CarReport.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _carReportId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _carId;
	private long _dealerId;
	private Date _viewDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CarReport, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CarReport)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("carReportId", _carReportId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("carId", _carId);
		_columnOriginalValues.put("dealerId", _dealerId);
		_columnOriginalValues.put("viewDate", _viewDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("carReportId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("carId", 256L);

		columnBitmasks.put("dealerId", 512L);

		columnBitmasks.put("viewDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CarReport _escapedModel;

}