/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.carservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CarReport service. Represents a row in the &quot;Car_CarReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.carservice.model.impl.CarReportModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.carservice.model.impl.CarReportImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CarReport
 * @generated
 */
@ProviderType
public interface CarReportModel
	extends BaseModel<CarReport>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a car report model instance should use the {@link CarReport} interface instead.
	 */

	/**
	 * Returns the primary key of this car report.
	 *
	 * @return the primary key of this car report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this car report.
	 *
	 * @param primaryKey the primary key of this car report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this car report.
	 *
	 * @return the uuid of this car report
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this car report.
	 *
	 * @param uuid the uuid of this car report
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the car report ID of this car report.
	 *
	 * @return the car report ID of this car report
	 */
	public long getCarReportId();

	/**
	 * Sets the car report ID of this car report.
	 *
	 * @param carReportId the car report ID of this car report
	 */
	public void setCarReportId(long carReportId);

	/**
	 * Returns the group ID of this car report.
	 *
	 * @return the group ID of this car report
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this car report.
	 *
	 * @param groupId the group ID of this car report
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this car report.
	 *
	 * @return the company ID of this car report
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this car report.
	 *
	 * @param companyId the company ID of this car report
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this car report.
	 *
	 * @return the user ID of this car report
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this car report.
	 *
	 * @param userId the user ID of this car report
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this car report.
	 *
	 * @return the user uuid of this car report
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this car report.
	 *
	 * @param userUuid the user uuid of this car report
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this car report.
	 *
	 * @return the user name of this car report
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this car report.
	 *
	 * @param userName the user name of this car report
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this car report.
	 *
	 * @return the create date of this car report
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this car report.
	 *
	 * @param createDate the create date of this car report
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this car report.
	 *
	 * @return the modified date of this car report
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this car report.
	 *
	 * @param modifiedDate the modified date of this car report
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the car ID of this car report.
	 *
	 * @return the car ID of this car report
	 */
	public long getCarId();

	/**
	 * Sets the car ID of this car report.
	 *
	 * @param carId the car ID of this car report
	 */
	public void setCarId(long carId);

	/**
	 * Returns the dealer ID of this car report.
	 *
	 * @return the dealer ID of this car report
	 */
	public long getDealerId();

	/**
	 * Sets the dealer ID of this car report.
	 *
	 * @param dealerId the dealer ID of this car report
	 */
	public void setDealerId(long dealerId);

	/**
	 * Returns the view date of this car report.
	 *
	 * @return the view date of this car report
	 */
	public Date getViewDate();

	/**
	 * Sets the view date of this car report.
	 *
	 * @param viewDate the view date of this car report
	 */
	public void setViewDate(Date viewDate);

	@Override
	public CarReport cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}